---
- name: Install WordPress on EC2 instance
  hosts: ec2-instance
  vars:
    db_name: wordpress
    db_user: wordpress
    db_password: password
    db_host: wordpress-stack-rdsinstance-tuayrglm9eqm.c02t1uqtbtct.us-east-1.rds.amazonaws.com
  tasks:
    - name: Install NFS utilities
      yum:
        name: nfs-utils
        state: present
      become: true

    - name: Create mount point for EFS
      file:
        path: /var/www/html
        state: directory
      become: true

    - name: Mount EFS to mount point
      mount:
        name: /var/www/html
        src: "fs-066e8e211309d0777.efs.us-east-1.amazonaws.com:/"
        fstype: nfs4
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
        state: mounted
      become: true

    - name: Install Apache, PHP, and MySQL client
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mysql
        state: present

    - name: Download and extract WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
      become: true

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: true
        extra_opts: --strip-components=1
      become: true

    - name: Set ownership and permissions for WordPress directory
      file:
        path: /var/www/html/
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes
      become: true

    - name: Copy WordPress configuration file
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wp-config.php
        owner: apache
        group: apache
        mode: '0644'
      become: true

    - name: Configure WordPress database connection
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: '^define\(\x27DB_NAME\x27'
        line: "define('DB_NAME', '{{ db_name }}');"
      become: true

    - name: Configure WordPress database connection
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: '^define\(\x27DB_USER\x27'
        line: "define('DB_USER', '{{ db_user }}');"
      become: true

    - name: Configure WordPress database connection
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: '^define\(\x27DB_PASSWORD\x27'
        line: "define('DB_PASSWORD', '{{ db_password }}');"
      become: true

    - name: Configure WordPress database connection
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: '^define\(\x27DB_HOST\x27'
        line: "define('DB_HOST', '{{ db_host }}');"
      become: true
