name: Deploy WordPress
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible
    - name: Run Ansible playbook
      run: ansible-playbook ansible/wordpress.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
